# Generated by Django 2.2 on 2022-03-16 13:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0009_test_is_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOnlineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('start_line', models.IntegerField(default=0)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_data', to='base.Test')),
            ],
        ),
    ]
