# Generated by Django 2.2.20 on 2021-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jmeterserver',
            old_name='jmeter_dir',
            new_name='jmeter_path',
        ),
        migrations.RemoveField(
            model_name='jmeterserver',
            name='project',
        ),
        migrations.AddField(
            model_name='jmeterserver',
            name='local_args',
            field=models.TextField(default=''),
        ),
    ]
