# Generated by Django 2.2.20 on 2021-06-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20210517_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmeterserver',
            name='loadgenerator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.LoadGenerator'),
        ),
        migrations.AlterField(
            model_name='jmeterserver',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Test'),
        ),
    ]
