# Generated by Django 2.2.20 on 2021-06-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20210603_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jmeterserver',
            name='loadgenerator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jmeter_servers', to='controller.LoadGenerator'),
        ),
    ]
