# Generated by Django 2.2 on 2022-03-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20210608_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proxy',
        ),
        migrations.RemoveField(
            model_name='testrunningdata',
            name='test_running',
        ),
        migrations.DeleteModel(
            name='TestRunning',
        ),
        migrations.DeleteModel(
            name='TestRunningData',
        ),
    ]
