# Generated by Django 5.2.17 on 2026-08-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20220316_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='jmeterserver',
            name='java_args',
            field=models.TextField(default=''),
        ),
    ]
