# Generated by Django 2.2.20 on 2021-04-30 13:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('jmeter_parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('script_parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('test_plan_destination', models.CharField(blank=True, max_length=200, null=True)),
                ('jvm_args', models.TextField(blank=True, null=True)),
                ('jmeter_remote_instances', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('script_pre', models.TextField(blank=True, null=True)),
                ('script_post', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('confluence_space', models.TextField(blank=True, null=True)),
                ('confluence_page', models.TextField(blank=True, null=True)),
                ('jmeter_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.JMeterProfile')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
