# Generated by Django 2.2.20 on 2021-05-05 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('confluence_space', models.TextField(blank=True, null=True)),
                ('confluence_page', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('status', models.CharField(choices=[('C', 'created'), ('R', 'running'), ('A', 'analyzing'), ('S', 'scheduled'), ('F', 'finished'), ('FA', 'failed')], default='C', max_length=12)),
                ('threads', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(db_index=True, null=True)),
                ('finished_at', models.DateTimeField(db_index=True, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('file_type', models.CharField(choices=[('O', 'online_result'), ('M', 'result'), ('L', 'log'), ('T', 'testplan'), ('J', 'jenkins_build_xml')], default='M', max_length=12)),
                ('file_size', models.IntegerField(default=0)),
                ('last_analyzed', models.DateTimeField(default=None, null=True)),
                ('last_analyzed_line', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Test')),
            ],
        ),
    ]
