# Generated by Django 2.2.20 on 2021-05-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210517_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='temp_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
