# Generated by Django 2.2.20 on 2021-05-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_test_temp_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='vars',
            field=models.JSONField(default=dict),
        ),
    ]
