# Generated by Django 2.2.20 on 2021-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_test_vars'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='last_active',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
