# Generated by Django 2.2.20 on 2021-05-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_reporttemplate_reportvariable'),
        ('base', '0005_test_last_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='confluence_page',
        ),
        migrations.RemoveField(
            model_name='project',
            name='confluence_space',
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='analyzer.ReportTemplate'),
        ),
    ]
