# Generated by Django 2.2 on 2022-03-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_project_project_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('value', models.CharField(default='', max_length=1000)),
                ('description', models.TextField()),
            ],
        ),
    ]
