# Generated by Django 2.2 on 2022-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_test_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='online_lines_analyzed',
            field=models.IntegerField(default=0),
        ),
    ]
