# Generated by Django 2.2 on 2022-03-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_test_online_lines_analyzed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
