# Generated by Django 2.2 on 2022-03-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220316_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='remote_temp_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
