# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 11:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JMeterTestPlanParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'jmeter_parameter',
            },
        ),
        migrations.CreateModel(
            name='LoadGeneratorServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=200)),
                ('ssh_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.SSHKey')),
            ],
            options={
                'db_table': 'load_generator_server',
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('destination', models.CharField(default='https://dest', max_length=200)),
                ('destination_port', models.IntegerField(default=443)),
                ('delay', models.FloatField()),
                ('started', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'proxy',
            },
        ),
        migrations.CreateModel(
            name='ScriptParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'script_parameter',
            },
        ),
        migrations.CreateModel(
            name='TestRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file_dest', models.CharField(default='', max_length=200)),
                ('monitoring_file_dest', models.CharField(default='', max_length=200)),
                ('log_file_dest', models.CharField(default='', max_length=200)),
                ('display_name', models.CharField(default='', max_length=100)),
                ('start_time', models.BigIntegerField()),
                ('pid', models.IntegerField(default=0)),
                ('jmeter_remote_instances', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('workspace', models.CharField(default='', max_length=200)),
                ('is_running', models.BooleanField(default=False)),
                ('build_number', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Project')),
            ],
            options={
                'db_table': 'test_running',
            },
        ),
    ]
