# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='destination',
            field=models.CharField(default='https://dest', max_length=200),
        ),
        migrations.AddField(
            model_name='proxy',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proxy',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
