# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 16:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_auto_20181109_1704'),
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrunning',
            name='build_path',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='testrunning',
            name='last_analyzed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='testrunning',
            name='testplan_file_dest',
            field=models.CharField(default='', max_length=200),
        ),
    ]
