# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_auto_20170328_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
