# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_auto_20170330_1533'),
        ('controller', '0003_proxy_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_file_path', models.CharField(default='', max_length=200)),
                ('display_name', models.CharField(default='', max_length=100)),
                ('start_time', models.BigIntegerField()),
                ('pid', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Project')),
            ],
            options={
                'db_table': 'test_running',
            },
        ),
    ]
