# Generated by Django 2.2 on 2021-04-29 13:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True)),
                ('code', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'error',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('jmeter_parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('script_parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('test_plan_destination', models.CharField(blank=True, max_length=200, null=True)),
                ('jvm_args', models.TextField(blank=True, null=True)),
                ('jmeter_remote_instances', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('script_pre', models.TextField(blank=True, null=True)),
                ('script_post', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
                ('confluence_space', models.TextField(blank=True, null=True)),
                ('confluence_page', models.TextField(blank=True, null=True)),
                ('jmeter_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrator.JMeterProfile')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'server',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('start_time', models.BigIntegerField(db_index=True)),
                ('end_time', models.BigIntegerField(default=0)),
                ('build_number', models.IntegerField(default=0)),
                ('show', models.BooleanField(default=True)),
                ('data_resolution', models.CharField(default='1Min', max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Project')),
                ('started_by', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administrator.User')),
            ],
            options={
                'db_table': 'test',
                'index_together': {('show', 'project', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TestDataResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=100)),
                ('per_sec_divider', models.IntegerField(default=60)),
            ],
            options={
                'db_table': 'test_data_resolution',
            },
        ),
        migrations.CreateModel(
            name='TestResultFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='test_result_files/')),
            ],
            options={
                'db_table': 'test_result_file',
            },
        ),
        migrations.CreateModel(
            name='TestError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Action')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Error')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'test_error',
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='default', max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_resolution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyzer.TestDataResolution')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'test_data',
            },
        ),
        migrations.CreateModel(
            name='TestAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'test_aggregate',
            },
        ),
        migrations.AddField(
            model_name='action',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyzer.Project'),
        ),
        migrations.CreateModel(
            name='TestActionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.Action')),
                ('data_resolution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyzer.TestDataResolution')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'test_action_data',
                'index_together': {('test', 'action', 'data_resolution')},
            },
        ),
        migrations.CreateModel(
            name='TestActionAggregateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Action')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'test_action_aggregate_data',
                'index_together': {('test', 'action')},
            },
        ),
        migrations.CreateModel(
            name='ServerMonitoringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='default', max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('data_resolution', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyzer.TestDataResolution')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Server')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'server_monitoring_data',
                'index_together': {('test', 'server', 'source', 'data_resolution')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('url', 'project')},
        ),
    ]
