# Generated by Django 2.2.20 on 2021-05-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('confluence_space', models.TextField(blank=True, null=True)),
                ('confluence_page', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variable_type', models.CharField(choices=[('G', 'graph'), ('V', 'value')], default='G', max_length=12)),
                ('params', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.ReportTemplate')),
            ],
            options={
                'unique_together': {('template', 'name')},
            },
        ),
    ]
