# Generated by Django 2.2.20 on 2021-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_reporttemplate_reportvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
