# Generated by Django 2.2.20 on 2021-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_graphitevariable_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphitevariable',
            name='rampup_include',
            field=models.BooleanField(default=True),
        ),
    ]
