# Generated by Django 2.2.20 on 2021-05-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210526_1446'),
        ('analyzer', '0007_graphitevariable_rampup_include'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Test')),
            ],
            options={
                'unique_together': {('test', 'name')},
            },
        ),
    ]
