# Generated by Django 2.2.20 on 2021-06-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_auto_20210603_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphitevariable',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='graphitevariable',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
