# Generated by Django 2.2.20 on 2021-06-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_auto_20210608_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphitevariable',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='graphitevariable',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
