from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^proxy/(?P<proxy_id>\d+)/set_delay/$', views.change_proxy_delay),
    url(r'^proxy/(?P<proxy_id>\d+)/start/$',
        views.start_proxy,
        name='start_proxy'),
    url(r'^proxy/(?P<proxy_id>\d+)/stop/$',
        views.stop_proxy,
        name='stop_proxy'),
    url(r'^proxy/new_proxy/$', views.new_proxy_page, name='new_proxy_page'),
    url(r'^proxy/new_proxy/add/$', views.add_proxy, name='new_proxy_page'),
    url(r'^$', views.controller_page),
    url(r'^new_project/$', views.create_project_page),
    url(r'^new_project/(?P<project_id>\d+)/create/$', views.create_project),
    url(r'^project/(?P<project_id>\d+)/delete/', views.delete_project),
    url(r'^running_test/(?P<running_test_id>\d+)/show_log/',
        views.show_log_page),
    url(r'^running_test/(?P<running_test_id>\d+)/get_log/(?P<log_type>[\w\-]+)/',
        views.running_test_log),
    url(r'^project/(?P<project_id>\d+)/configure_test$', views.configure_test),
    url(r'^project/(?P<project_id>\d+)/start_test', views.start_test),
    url(r'^project/(?P<project_id>\d+)/new_jri/$', views.new_jri_page),
    url(r'^project/(?P<project_id>\d+)/new_jmeter_param/$',
        views.new_jmeter_param_page),
    url(r'^project/(?P<project_id>\d+)/new_script_param/$',
        views.new_script_param_page),
    url(r'^project/(?P<project_id>\d+)/new_jri/add/$', views.add_jri),
    url(r'^project/(?P<project_id>\d+)/script_pre_configure/$',
        views.script_pre_configure),
    url(r'^project/(?P<project_id>\d+)/script_post_configure/$',
        views.script_post_configure),
    url(r'^project/(?P<project_id>\d+)/script_pre_save/$',
        views.script_pre_save),
    url(r'^project/(?P<project_id>\d+)/script_post_save/$',
        views.script_post_save),
    url(r'^project/(?P<project_id>\d+)/jmeter_params/add/$',
        views.add_jmeter_param),
    url(r'^project/(?P<project_id>\d+)/script_params/add/$',
        views.add_script_param),
    url(r'^project/(?P<project_id>\d+)/jri/list/$', views.jri_list),
    url(r'^project/(?P<project_id>\d+)/jmeter_params/list/$',
        views.jmeter_params_list),
    url(r'^project/(?P<project_id>\d+)/script_params/list/$',
        views.script_params_list),
    url(r'^project/(?P<project_id>\d+)/jri/(?P<jri_id>\d+)/delete/$',
        views.jri_delete),
    url(r'^project/(?P<project_id>\d+)/jmeter_params/(?P<param_id>\d+)/delete/$',
        views.jmeter_param_delete),
    url(r'^project/(?P<project_id>\d+)/script_params/(?P<param_id>\d+)/delete/$',
        views.script_param_delete),
    url(r'^running_test/(?P<running_test_id>\d+)/stop_test', views.stop_test),
]
