# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 10:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'action',
            },
        ),
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.FloatField()),
                ('median', models.FloatField()),
                ('percentile_75', models.FloatField()),
                ('percentile_90', models.FloatField()),
                ('percentile_99', models.FloatField()),
                ('maximum', models.FloatField()),
                ('minimum', models.FloatField()),
                ('count', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('weight', models.FloatField()),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.Action')),
            ],
            options={
                'db_table': 'aggregate',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'server',
            },
        ),
        migrations.CreateModel(
            name='ServerMonitoringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Server')),
            ],
            options={
                'db_table': 'server_monitoring_data',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=100)),
                ('start_time', models.BigIntegerField()),
                ('build_number', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Project')),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.CreateModel(
            name='TestActionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.Action')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'test_action_data',
            },
        ),
        migrations.CreateModel(
            name='TestAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'test_aggregate',
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test')),
            ],
            options={
                'db_table': 'test_data',
            },
        ),
        migrations.AddField(
            model_name='servermonitoringdata',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test'),
        ),
        migrations.AddField(
            model_name='aggregate',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Test'),
        ),
        migrations.AlterIndexTogether(
            name='testactiondata',
            index_together=set([('test', 'action')]),
        ),
        migrations.AlterUniqueTogether(
            name='aggregate',
            unique_together=set([('test', 'action')]),
        ),
    ]
