# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_auto_20170317_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregate',
            name='errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
