# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_auto_20170327_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
